Repository theohbrothers/docker-terraform, pull requests merged in 2023-09, with the labels that each got.

#37 Refactor: Move versions from `VARIANTS.ps1` to `versions.json`
  generate/definitions/VARIANTS.ps1
  generate/definitions/versions.json
Labels: refactor

#38 Enhancement (ci): Add `Update-Versions.ps1` and `cron` job
  .github/workflows/cron.yml
  Update-Versions.ps1
  generate/definitions/FILES.ps1
  generate/templates/.github/workflows/cron.yml.ps1
Labels: enhancement

#40 Enhancement: Bump v1.5 variants to v1.5.7
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v1.5.7-jq-libvirt-sops-ssh/Dockerfile
  variants/v1.5.7-jq-sops-ssh/Dockerfile
  variants/v1.5.7/Dockerfile
Labels: enhancement

#41 Enhancement: Bump v1.4 variants to v1.4.7
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v1.4.7-jq-libvirt-sops-ssh/Dockerfile
  variants/v1.4.7-jq-sops-ssh/Dockerfile
  variants/v1.4.7/Dockerfile
Labels: enhancement

#42 Enhancement: Bump v1.3 variants to v1.3.10
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/v1.3.10-jq-libvirt-sops-ssh/Dockerfile
  variants/v1.3.10-jq-sops-ssh/Dockerfile
  variants/v1.3.10/Dockerfile
Labels: enhancement

#39 Enhancement (ci): Add `on: merge_group` for merge queue support
  .github/workflows/ci-master-pr.yml
  generate/templates/.github/workflows/ci-master-pr.yml.ps1
Labels: enhancement

#43 Docs (readme): Update Variant versions section
  README.md
  generate/templates/README.md.ps1
Labels: docs

#44 Enhancement (ci): Remove ` $env:GITHUB_TOKEN` in `Update-Versions.ps1`
  Update-Versions.ps1
Labels: enhancement

#45 Refactor (ci): Use new `versions.json` config
  Update-Versions.ps1
  generate/definitions/VARIANTS.ps1
  generate/definitions/versions.json
Labels: refactor

#46 Enhancement (ci): Add `workflow_dispatch` to `cron` job
  .github/workflows/cron.yml
  generate/templates/.github/workflows/cron.yml.ps1
Labels: enhancement

#47 Enhancement (ci): Add support for incremental variants
  .github/workflows/ci-master-pr.yml
  generate/templates/.github/workflows/ci-master-pr.yml.ps1
Labels: enhancement

#48 Refactor (ci): Use a `job_group_key` to group jobs
  .github/workflows/ci-master-pr.yml
  .vscode/tasks.json
  generate/definitions/VARIANTS.ps1
  generate/templates/.github/workflows/ci-master-pr.yml.ps1
Labels: refactor
