Repository theohbrothers/docker-terraform, pull requests merged in 2023-12, with the labels that each got.

#59 Refactor: Move functions to `./generate/functions`
  generate/functions/Checksums.ps1
  generate/functions/Generate-DownloadBinary.ps1
  generate/templates/Dockerfile.ps1
Labels: refactor

#60 Enhancement: Bump `Generate-DownloadBinary` function to 0.1.0
  generate/functions/Generate-DownloadBinary.ps1
  variants/0.10.8-jq-libvirt-sops-ssh/Dockerfile
  variants/0.10.8-jq-sops-ssh/Dockerfile
  variants/0.10.8/Dockerfile
  variants/0.11.15-jq-libvirt-sops-ssh/Dockerfile
  variants/0.11.15-jq-sops-ssh/Dockerfile
  variants/0.11.15/Dockerfile
  variants/0.12.31-jq-libvirt-sops-ssh/Dockerfile
  variants/0.12.31-jq-sops-ssh/Dockerfile
  variants/0.12.31/Dockerfile
  variants/0.13.7-jq-libvirt-sops-ssh/Dockerfile
  variants/0.13.7-jq-sops-ssh/Dockerfile
  variants/0.13.7/Dockerfile
  variants/0.14.11-jq-libvirt-sops-ssh/Dockerfile
  variants/0.14.11-jq-sops-ssh/Dockerfile
  variants/0.14.11/Dockerfile
  variants/0.15.5-jq-libvirt-sops-ssh/Dockerfile
  variants/0.15.5-jq-sops-ssh/Dockerfile
  variants/0.15.5/Dockerfile
  variants/0.8.8-jq-libvirt-sops-ssh/Dockerfile
  variants/0.8.8-jq-sops-ssh/Dockerfile
  variants/0.8.8/Dockerfile
  variants/0.9.11-jq-libvirt-sops-ssh/Dockerfile
  variants/0.9.11-jq-sops-ssh/Dockerfile
  variants/0.9.11/Dockerfile
  variants/1.0.11-jq-libvirt-sops-ssh/Dockerfile
  variants/1.0.11-jq-sops-ssh/Dockerfile
  variants/1.0.11/Dockerfile
  variants/1.1.9-jq-libvirt-sops-ssh/Dockerfile
  variants/1.1.9-jq-sops-ssh/Dockerfile
  variants/1.1.9/Dockerfile
  variants/1.2.9-jq-libvirt-sops-ssh/Dockerfile
  variants/1.2.9-jq-sops-ssh/Dockerfile
  variants/1.2.9/Dockerfile
  variants/1.3.10-jq-libvirt-sops-ssh/Dockerfile
  variants/1.3.10-jq-sops-ssh/Dockerfile
  variants/1.3.10/Dockerfile
  variants/1.4.7-jq-libvirt-sops-ssh/Dockerfile
  variants/1.4.7-jq-sops-ssh/Dockerfile
  variants/1.4.7/Dockerfile
  variants/1.5.7-jq-libvirt-sops-ssh/Dockerfile
  variants/1.5.7-jq-sops-ssh/Dockerfile
  variants/1.5.7/Dockerfile
  variants/1.6.5-jq-libvirt-sops-ssh/Dockerfile
  variants/1.6.5-jq-sops-ssh/Dockerfile
  variants/1.6.5/Dockerfile
Labels: enhancement

#61 Docs: Update spelling in Update-Versions.ps1
  Update-Versions.ps1
Labels: docs

#62 Enhancement: Bump terraform 1.6 variants to 1.6.6
  .github/workflows/ci-master-pr.yml
  README.md
  generate/definitions/versions.json
  variants/1.6.6-jq-libvirt-sops-ssh/Dockerfile
  variants/1.6.6-jq-sops-ssh/Dockerfile
  variants/1.6.6/Dockerfile
Labels: enhancement
